image: node:16

stages:
  - test
  - production

test:
  type: test
  stage: test
  services:
    - postgres:latest
  variables:
    RAILS_ENV: test
    POSTGRES_DB: d7b3rfmfrl9lg9
    POSTGRES_USER: xvsfwnejwomjsr
    POSTGRES_PASSWORD: 02afa491f2cd55d14e119ebd1ebc3a3916b049f7b79d8dcdf955a60cfb33bda6
    POSTGRES_HOST_AUTH_METHOD: trust
    DATABASE_URL: "postgres://xvsfwnejwomjsr:02afa491f2cd55d14e119ebd1ebc3a3916b049f7b79d8dcdf955a60cfb33bda6@ec2-44-199-85-33.compute-1.amazonaws.com:5432/d7b3rfmfrl9lg9"
  script:
    - npm i
    - npm run test
  only:
    - development

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY_FALAH
  only:
    - development
